// config module
export const RECEIVE_ACCOUNT = 'RECEIVE_ACCOUNT'
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG'
export const UPDATE_CONFIG = 'UPDATE_CONFIG'

// purchases module
export const WORK_SYNCING = 'WORK_SYNCING'
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT'
export const UPDATE_CONDITIONS = 'UPDATE_CONDITIONS'
export const INCREMENT_PAGE = 'INCREMENT_PAGE'

// work module
export const GET_WORK_IMAGE = 'GET_WORK_IMAGE'
export const OPEN_WORK_DATA = 'OPEN_WORK_DATA'
export const CLOSE_WORK_DATA = 'CLOSE_WORK_DATA'
export const RECEIVE_META = 'RECEIVE_META'
export const RECEIVE_ZIPTREE = 'RECEIVE_ZIPTREE'
export const ADD_CACHE_FILE_LIST = 'ADD_CACHE_FILE_LIST'
export const UPDATE_CACHE_FILE_URL = 'UPDATE_CACHE_FILE_URL'
export const ADD_CACHE_FILE_QUEUE = 'ADD_CACHE_FILE_QUEUE'
export const UPDATE_CACHE_FILE_STATUS = 'UPDATE_CACHE_FILE_STATUS'
export const SHIFT_CACHE_FILE_QUEUE = 'SHIFT_CACHE_FILE_QUEUE'
export const COMPLETE_CACHE_FILE_QUEUE = 'COMPLETE_CACHE_FILE_QUEUE'
export const RECIVE_CACHE_FILE_INFO = 'RECIVE_CACHE_FILE_INFO'

// audio module
export const LOADING_STATUS = 'LOADING_STATUS'
export const POSITION = 'POSITION'
export const DURATION = 'DURATION'
export const PLAYING = 'PLAYING'
export const SET_PLAYLIST = 'PLAYLIST'
export const SET_ORIGIN_PLAYLIST = 'SET_ORIGIN_PLAYLIST'
export const SET_INDEX = 'SET_INDEX'
export const SET_CONFIG = 'SET_CONFIG'

// mylist module
export const RECEIVE_MYLIST = 'RECEIVE_MYLIST'
export const INSERT_MYLIST = 'INSERT_MYLIST'
export const UPDATE_MYLIST = 'UPDATE_MYLIST'
export const RECEIVE_MYLIST_WORK = 'RECEIVE_MYLIST_WORK'
export const CLOSE_MYLIST = 'CLOSE_MYLIST'

// playlist module
export const RECEIVE_PLAYLIST = 'RECEIVE_PLAYLIST'
export const INSERT_PLAYLIST = 'INSERT_PLAYLIST'
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST'
export const RECEIVE_PLAYLIST_WORK = 'RECEIVE_PLAYLIST_WORK'
export const CLOSE_PLAYLIST = 'CLOSE_PLAYLIST'

// cien module
export const CIEN_MAKERS = 'CIEN_MAKERS'

// recommendation module
export const RECOMMEND_FOR_PERSON = 'RECOMMEND_FOR_PERSON'
export const RECOMMEND_FOR_PRODUCT = 'RECOMMEND_FOR_PRODUCT'
export const RECOMMEND_FOR_NEXT = 'RECOMMEND_FOR_NEXT'

// menu module
export const MENU_SHOWN_DOWNLOAD = 'MENU_SHOWN_DOWNLOAD'

// ignore module
export const IGNORED_WORKS = 'IGNORED_WORKS'
